language: python
python:
  - "3.6"

services:
  - docker

script: make test

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - feeltheajf:KtpBSt1d694nkztes1h4Nbn0#ci
