language: python
python:
  - "3.7"

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

services:
  - docker

script: make test

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - feeltheajf:KtpBSt1d694nkztes1h4Nbn0#ci
